name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-RC*"

jobs:
  buildWin:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go version

      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -o ieftool-windows-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: ieftool-windows-amd64
          path: ieftool-windows-amd64

  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go version

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o ieftool-linux-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: ieftool-linux-amd64
          path: ieftool-linux-amd64
  buildMac:
    name: Build Mac (Intel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go version

      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -o ieftool-darwin-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: ieftool-darwin-amd64
          path: ieftool-darwin-amd64
  buildMacArm:
    name: Build Mac (ARM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.22.0'
      - run: go version

      - name: Build
        run: |
          GOOS=darwin GOARCH=arm64 go build -o ieftool-darwin-arm64
      - uses: actions/upload-artifact@v2
        with:
          name: ieftool-darwin-arm64
          path: ieftool-darwin-arm64

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ buildMacArm,buildMac,buildLinux,buildWin ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ieftool-windows-amd64
      - uses: actions/download-artifact@v2
        with:
          name: ieftool-linux-amd64
      - uses: actions/download-artifact@v2
        with:
          name: ieftool-darwin-amd64
      - uses: actions/download-artifact@v2
        with:
          name: ieftool-darwin-arm64
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ieftool-windows-amd64
            ieftool-linux-amd64
            ieftool-darwin-amd64
            ieftool-darwin-arm64